
server:
  port: 8005
spring:
  application:
    name: kitty-consumer
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
  boot:
    admin:
      client:
        url: http://localhost:8000
  zipkin:
    base-url: http://192.168.0.104:9411/
  sleuth:
    sampler:
      probability: 1  #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: true

#ribbon 随机算法
#service-producer:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
