
server:
  port: 8010
spring:
  application:
    name: kitty-zuul
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
zuul:
  routes:
    ribbon:
      path: /ribbon/**
      service_id: kitty-consumer    # \u8F6C\u53D1\u5230\u6D88\u8D39\u8005 /ribbon/
    feign:
      path: /feign/**
      service_id: kitty-consumer       # \u8F6C\u53D1\u5230\u6D88\u8D39\u8005 /feign/
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 10000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 3000

